services:
  kusov-ws:
    image: kusov-ws:latest
    container_name: kusov-ws
    hostname: kusov-ws
    stdin_open: true
    tty: true
    volumes:
      - ${WORKDIR_VOLUME}:/home/kusov/workdir
    build:
      context: .
      ssh:
        - default
