services:
  ide:
    image: ide:latest
    container_name: ide
    hostname: ide
    stdin_open: true
    tty: true
    volumes:
      - ${PWD}:/home/${USER_NAME:-me}/workdir
      - ${HOME}/.ssh:/home/${USER_NAME:-me}/.ssh
      - ${HOME}/.gitconfig:/home/${USER_NAME:-me}/.gitconfig
    build:
      context: .
      args:
        USER_NAME: ${USER_NAME:-me}
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
